### ISSUE TITLE
Single click breaks tagging

### ISSUE THREAD

**Issue by Josh-Henly** [iionly/Elgg_1.9_tidypics#12]
If a user starts the Tag feature and then clicks the image instead of selecting an area, the colorbox is opened and text can't be typed in the tag box (at least in FF and Safari).  It acts as though the colorbox overlay has a higher z-index than the tidypics-tagging-select div -- though that isn't actually the case (1100 for the overlay vs 9999 for the tidypics div).

Once the colorbox overlay is closed, then it becomes possible to enter text in the tagging box.

**Comment by iionly** [comment]
Fixed with https://github.com/iionly/Elgg_1.9_tidypics/commit/7ba9180966be2b36dd4fc15f2b19dca027e59acd. This commit will be part of the next release 1.9.5 of Tidypics.
