### ISSUE TITLE
pages/siteimagesowner shouldn't be accessible when not logged in

### ISSUE THREAD

**Issue by Josh-Henly** [iionly/Elgg_1.9_tidypics#13]
See screenshot re: "'s photos":

![screen shot 2014-12-08 at 1 35 49 pm](https://cloud.githubusercontent.com/assets/4510430/5345253/4379a518-7ee4-11e4-8e53-6b77d99063c4.png)

**Comment by iionly** [comment]
Fixed by commit https://github.com/iionly/Elgg_1.9_tidypics/commit/fec406ddb52c50c837f8d464536b32c69ebbcaec which will be included in version 1.9.5.
