### ISSUE TITLE
Upgrade hangs on 1.9.4.1

### ISSUE THREAD

**Issue by Josh-Henly** [iionly/Elgg_1.9_tidypics#14]
On my 1.8.19 site, I:

- disabled the Tidypics plugin on the admin page
- removed the old mod/tidypics folder, replaced it with version 1.9.4.1
- upgraded my site to 1.9.5
- re-enabled the Tidypics plugin
- ran the site upgrade scripts (including the Comments upgrade)
- ran the Tidypics upgrade script (clicked the 'Upgrade' link on admin/Tidypics/Settings page)

The upgrade hangs on step 4/5 of upgrades/2014111701.php.  The 'foreach ($batch as $album_comment)' loop repeats infinitely on the first chunk of 25 items.  $river_entry_count is == 1 on all 25 items, so we never call $album_comment->delete() (not that it should matter, since $batch->setIncrementOffset(false) was set).

**Comment by iionly** [comment]
Fix added with commit https://github.com/iionly/Elgg_1.9_tidypics/commit/a233e0350d76192b8e2633d441b74a4e5c0bf42a. It will be included in the next version 1.9.5 of Tidypics.
