### ISSUE TITLE
Move files to root dir

### ISSUE THREAD

**Issue by ewinslow** [iionly/Elgg_1.9_tidypics#17]
Everything being under a tidypics subfolder makes it harder to just `git clone` the repo into my Elgg site. Putting all the plugin files at the root level of the package would help alleviate that pain.

**Comment by iionly** [comment]
Done in https://github.com/iionly/Elgg_1.9_tidypics/commit/2fce0eb1187d7dfe14751a25acd3a89f380e0811.

Though it now me who has to change his style of work...
