### ISSUE TITLE
An user  should be able to tag his own photo only

### ISSUE THREAD

**Issue by dranii** [iionly/Elgg_1.9_tidypics#7]
One user can tag on another user's photo ( tag = directly mark on photo) - users should be able to tag his own photo

**Comment by iionly** [comment]
With commit https://github.com/iionly/Elgg_1.9_tidypics/commit/0224d283779081da91583b9fe34c862f25b87fa4 I've added a new plugin setting that allows restricting tagging to a user's own photos only. This will be part of the next release 1.9.5 of Tidypics.
