### ISSUE TITLE
 tagging (marking on photo) is difficult - the selection area is not seen

### ISSUE THREAD

**Issue by dranii** [iionly/Elgg_1.9_tidypics#8]
Using the latest FF tagging (marking on photo) is difficult - the selection area is not seen  when dragging the cursor (previous versions of tidypics did not have this problem)

**Comment by iionly** [comment]
Fixed with https://github.com/iionly/Elgg_1.9_tidypics/commit/e858ceca511f755882f654a400f7bbbe2e91122e which will be included in next version 1.9.5.
