### ISSUE TITLE
Tagging and marking on photo both comes under the Tags under the poster name and time stamp

### ISSUE THREAD

**Issue by dranii** [iionly/Elgg_1.9_tidypics#9]
This causes confusion as to which is text tag and which is marking on photo.
When you edit photo you can remove both tags from the edit tag text area but the tag, that is marking on photo, still remains.

**Comment by iionly** [comment]
Commit https://github.com/iionly/Elgg_1.9_tidypics/commit/368f4e318cce8a4c79363bcfad8099478c2d336d improves the labels of wordtags and tagged members. This commit will be part of the next version 1.9.5 of Tidypics.

The tags on the image (both wordtags and member tags) can be deleted directly via the X icon by users who have edit right on the image (image owner or admin or group members in case of group albums). Removing a wordtag also removes these tags from the list of tags that is displayed in the image title section.
